apiVersion: v1
kind: Service
metadata:
  name: extract-links-service
  labels:
    app: extract-links
spec:
  selector:
    app: extract-links
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
